#! /bin/bash

# Change this to match your root directory of the flag_gpu repo
if [ $# -eq 0 ] # No arguments provided
then
    FLAG_DIR=$PWD
else
    FLAG_DIR=$1
fi

# Change this to match your destination directory
prefix=$HOME/hash

# Add prefix to PATH
if [[ "$PATH" == ?(*:)"$prefix/bin"?(:*) ]]
then
    echo "PATH includes $prefix/bin"
else
    echo "PATH does not include $prefix/bin... Adding now"
    export PATH=$prefix/bin:$PATH
fi

# Add prefix to LD_LIBRARY_PATH
if [[ "$LD_LIBRARY_PATH" == ?(*:)"$prefix/lib"?(:*) ]]
then
    echo "LD_LIBRARY_PATH includes $prefix/lib"
else
    echo "LD_LIBRARY_PATH does not include $prefix/lib... Adding now"
    export LD_LIBRARY_PATH=$prefix/lib:$LD_LIBRARY_PATH
fi

# Check for CUDA
if [ -z "$CUDA" ]
then
    echo "CUDA is not set-- using $prefix/cuda"
    CUDA=$prefix/cuda
else
    echo "CUDA is set to $CUDA"
fi

# Set library source directories
HASHPIPE_SRC=$FLAG_DIR/lib/hashpipe/src
XGPU_SRC=$FLAG_DIR/lib/xGPU/src
BEAM_SRC=$FLAG_DIR/lib/beamformer/src
PFB_SRC=$FLAG_DIR/lib/pfb/src
POWER_SRC=$FLAG_DIR/lib/flagPower/src

# Compile the hashpipe library
echo "Installing HASHPIPE"
echo "========================================"
echo "Navigating to $HASHPIPE_SRC"
cd $HASHPIPE_SRC
autoreconf -is
./configure --prefix=$prefix --silent
make clean
make
make install
echo "========================================"
echo 

# Compile the xGPU library
echo "Installing xGPU"
echo "========================================"
echo "Navigating to $XGPU_SRC"
cd $XGPU_SRC
make clean
make
make install prefix=$prefix
echo "========================================"
echo 

# Compile the beamformer library
echo "Installing flagbeamformer"
echo "========================================"
echo "Navigating to $BEAM_SRC"
cd $BEAM_SRC
make clean
make
make install prefix=$prefix
echo "========================================"
echo 

# Compile the flagPower library
echo "Installing flagPower"
echo "========================================"
echo "Navigating to $POWER_SRC"
cd $POWER_SRC
make clean
make
make install prefix=$prefix
echo "========================================"
echo 

# Compile the pfb library
echo "Installing flagpfb"
echo "========================================"
echo "Navigating to $PFB_SRC"
cd $PFB_SRC
make clean
make CUDA_DIR=$CUDA
make install prefix=$prefix CUDA_DIR=$CUDA
echo "========================================"
echo

# Compile the flag HASHPIPE plugins
echo "Installing the FLAG plugins"
echo "========================================"
echo "Navigating to $FLAG_DIR/src"
cd $FLAG_DIR/src
autoreconf -is
./configure --prefix=$prefix --with-hashpipe=$prefix --with-xgpu=$prefix --with-xgpufrb=$prefix --with-xgpupfb=$prefix --with-flagpfb=$prefix --with-flagbeamformer=$prefix --with-flagpower=$prefix --silent
make clean
make
make install
echo "========================================"
echo 

cd $FLAG_DIR

echo "DONE!"
echo "The FLAG plugins have been installed to $prefix"
