#! /bin/bash

# Change this to match your root directory of the flag_gpu repo
if [ $# -eq 0 ] # No arguments provided
then
    FLAG_DIR=$PWD
else
    FLAG_DIR=$1
fi

# Change this to match your destination directory
prefix=~/hash

# Set library source directories
HASHPIPE_SRC=$FLAG_DIR/lib/hashpipe/src
XGPU_SRC=$FLAG_DIR/lib/xGPU/src
BEAM_SRC=$FLAG_DIR/lib/beamformer/src
PFB_SRC=$FLAG_DIR/lib/pfb/src
POWER_SRC=$FLAG_DIR/lib/flagPower/src

# Compile the hashpipe library
echo "Installing HASHPIPE"
echo "========================================"
echo "Navigating to $HASHPIPE_SRC"
cd $HASHPIPE_SRC
autoreconf -is
./configure --prefix=$prefix --silent
make
make install
echo "========================================"
echo 

# Compile the xGPU library
echo "Installing xGPU"
echo "========================================"
echo "Navigating to $XGPU_SRC"
cd $XGPU_SRC
make
make install prefix=$prefix
echo "========================================"
echo 

# Compile the beamformer library
echo "Installing flagbeamformer"
echo "========================================"
echo "Navigating to $BEAM_SRC"
cd $BEAM_SRC
make
make install prefix=$prefix
echo "========================================"
echo 

# Compile the flagPower library
echo "Installing flagPower"
echo "========================================"
echo "Navigating to $POWER_SRC"
cd $POWER_SRC
make
make install prefix=$prefix
echo "========================================"
echo 

# Compile the pfb library
echo "Installing flagpfb"
echo "========================================"
echo "Navigating to $PFB_SRC"
cd $PFB_SRC
make
make install prefix=$prefix
echo "========================================"
echo

# Compile the flag HASHPIPE plugins
echo "Installing the FLAG plugins"
echo "========================================"
echo "Navigating to $FLAG_DIR/src"
cd $FLAG_DIR/src
autoreconf -is
./configure --prefix=$prefix --with-hashpipe=$prefix --with-xgpu=$prefix --with-xgpufrb=$prefix --with-xgpupfb=$prefix --with-flagpfb=$prefix --with-flagbeamformer=$prefix --with-flagpower=$prefix --silent
make
make install
echo "========================================"
echo 

echo "DONE!"
echo "The FLAG plugins have been installed to $prefix"
